### ISSUE TITLE
Requesting inaccurate paths from js causes routing errors

### ISSUE THREAD

**Issue by mockdeep** [internetarchive/heritrix3#155]
Not sure if this is the place for this issue, but we're seeing elevated routing errors coming from a Heretrix user agent that is trying to request random `require` lines from our application javascript.  One example is from some minified reactjs code:

```js
c=t("./ReactComponent"),d=t("./ReactElement"),h=(t("./ReactPropTypeLocations"),t("./ReactPropTypeLocationNames"),t("./ReactNoopUpdateQueue"))
```

Heretrix tries to get these non-existent assets from our servers:

```
ActionController::RoutingError: No route matches [GET] "/ReactNoopUpdateQueue"
```

Not sure what to do about this aside from just blocking Heretrix up front.

**Comment by nlevitt** [comment]
Heritrix looks for strings in javascript that look like urls, if configured to do so. We have put some effort into tuning the heuristic that decides if a string is likely to be a url. There's a balance to be struck between getting as much good content as possible and avoiding 404s. But inevitably, heritrix will try  some nonsense urls.

Are these requests really a problem for your server? You could block heritrix from the bad urls, or from your whole site if necessary, with a robots.txt.

**Comment by mockdeep** [comment]
It's just noise, we get elevated routing errors every time Heritrix visits our site. We'll just block the user agent.
