### ISSUE TITLE
Can't see all beans in scripts

### ISSUE THREAD

**Issue by sagnik** [internetarchive/heritrix3#157]
I was trying to execute the following code from https://webarchive.jira.com/wiki/display/Heritrix/Heritrix3+Useful+Scripts#Heritrix3UsefulScripts-addasheetforcingmanyqueuesinto'retired'state 

```
mgr = appCtx.getBean("sheetOverlaysManager");
newSheetName = "urbanOrgAndTaxpolicycenterOrgSingleQueue"
mgr.putSheetOverlay(newSheetName, "queueAssignmentPolicy.forceQueueAssignment", "urbanorg_and_taxpolicycenterorg");
mgr.addSurtAssociation("http://(org,urban,", newSheetName);
mgr.addSurtAssociation("http://(org,taxpolicycenter,", newSheetName);
 
//check your results
mgr.sheetNamesBySurt.each{ rawOut.println(it) }
rawOut.println(mgr.sheetNamesBySurt.size())

```

This gives the following error:  `javax.script.ScriptException: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'queueAssignmentPolicy' is defined`. 

It appears to me that any bean that is within comment ( they are default values and can be kept untouched for common use cases, I think) in the default configuration file can not be accessed through the Groovy script. Is this an intentional behavior? Is there any way to get and change these values?

**Comment by nlevitt** [comment]
Hello @sagnik. "queueAssignmentPolicy" isn't a top-level bean, it's a member of "preparer". Try
`rawOut.println(preparer.queueAssignmentPolicy)`
And btw notice that you can put bean names in directly as variable names omitting the `appCtx.getBean("...")` part. We ought to fix that wiki page...
