### ISSUE TITLE
Missing OneLineSimpleLayout class file

### ISSUE THREAD

**Issue by heitorganzeli** [internetarchive/heritrix3#173]
Hi,

I was trying to build the master branch with `mvn package` but the tests of the subproject commons failed due to a NoClassDefFoundError. The missing class was org.archive.util.OneLineSimpleLayout.

This class is listed on the commons/src/test/resources/log4j.xml configuration file but it does not exist on the src. it is placed only at the contrib folder.

**Comment by heitorganzeli** [comment]
My bad, tested it with a clean clone and it worked just fine!

closing the issue

**Comment by anjackson** [comment]
Hm in #175 this still seems to be an issue. Where is that class in your clean clone? AFAICT it's still in the wrong place. https://github.com/internetarchive/heritrix3/search?utf8=%E2%9C%93&q=OneLineSimpleLayout&type=Code

**Comment by heitorganzeli** [comment]
Yeah, latter I've noticed that the class being in the wrong place doesn't break the build. but the class can be found at: https://github.com/internetarchive/heritrix3/blob/fbb0173459b698b1bb9fcedf4ea3c4ac7b5f0cf6/contrib/src/main/java/org/archive/util/OneLineSimpleLayout.java

**Comment by anjackson** [comment]
Thanks. A non-fatal error but it would still be good to clean it up.

**Comment by ato** [comment]
This looks like it was fixed by d85d2a3 in #190.
