### ISSUE TITLE
heritrix doesn't scrape rewrite srcset urls correctly

### ISSUE THREAD

**Issue by nightpool** [internetarchive/heritrix3#177]
Reposted from https://github.com/internetarchive/wayback/issues/137 as I learn more about the architecture here.

I ran into an issue while trying to archive the website [http://www.goodbyetohalos.com](http://www.goodbyetohalos.com). Like many webcomics using wordpress nowadays, Goodbye to Halos uses html5 srcset attributes to displays different image sizes to different devices:

```html
<img
    width="800" height="1200" 
    src="http://www.goodbyetohalos.com/wp-content/uploads/2017/01/WEB_ch1_108.jpg"
    class="attachment-full size-full" alt=""
    srcset="http://www.goodbyetohalos.com/wp-content/uploads/2017/01/WEB_ch1_108.jpg 800w,
            http://www.goodbyetohalos.com/wp-content/uploads/2017/01/WEB_ch1_108-480x720.jpg 480w,
            http://www.goodbyetohalos.com/wp-content/uploads/2017/01/WEB_ch1_108-96x144.jpg 96w"
    sizes="(max-width: 800px) 100vw, 800px"
    data-webcomic-parent="837"
>
```

so far, so good. *however*, after crawling/scraping these with wayback, only the src url is scraped and rewritten, leading to the image on wayback'ed page still being served from the original server:

```html
<img
    width="800" height="1200"
    src="/web/20170127042412im_/http://www.goodbyetohalos.com/wp-content/uploads/2017/01/WEB_ch1_108.jpg"
    class="attachment-full size-full" alt=""
    srcset="http://www.goodbyetohalos.com/wp-content/uploads/2017/01/WEB_ch1_108.jpg 800w,
            http://www.goodbyetohalos.com/wp-content/uploads/2017/01/WEB_ch1_108-480x720.jpg 480w,
            http://www.goodbyetohalos.com/wp-content/uploads/2017/01/WEB_ch1_108-96x144.jpg 96w"
    sizes="(max-width: 800px) 100vw, 800px"
    data-webcomic-parent="837"
>
```

this is very obvious because the original site doesn't use https, so it leads to a broken image on the wayback machine view:

![image](https://cloud.githubusercontent.com/assets/233815/22360672/035fd242-e420-11e6-88b9-57c20d03a13f.png)

Obviously, the correct behavior here is that all of the images should be scraped (in this case they're just resizings, but in theory they could be completely different images—nothing prevents that) and rewritten.

Thanks! let me know if you need more information, or want me to whip up a more minimal test case

**Comment by BitBaron** [comment]
Thank you for the issue @nightpool. Yes, this is a known issue and we're working on incorporating `srcset` scraping into a future build (_coming soon_).

I'll post again when we have a working build for you.

**Comment by BitBaron** [comment]
@nightpool, the most recent builds of Heritirix now included crawling for `srcset` values. It was released as part of https://github.com/internetarchive/heritrix3/pull/179.

**Comment by nightpool** [comment]
Thanks for the update! Feel free to close the issue when you think it's been resolved.
