### ISSUE TITLE
Google Drive robots.txt broken

### ISSUE THREAD

**Issue by nightpool** [internetarchive/heritrix3#193]
Robots txt parsing is broken for google drive. Here's the directives:

```
User-agent: *
Crawl-delay: 1
Allow: /$
Allow: /?hl=
Disallow: /?hl=*&
Allow: /support/
Allow: /a/
Allow: /Doc
Allow: /View
Allow: /ViewDoc
Allow: /present
Allow: /Present
Allow: /TeamPresent
Allow: /EmbedSlideshow
Allow: /presentation
Allow: /templates
Allow: /previewtemplate
Allow: /fileview
Allow: /gview
Allow: /viewer
Allow: /leaf
Allow: /file
Allow: /open
Allow: /document
Allow: /drawings
Allow: /demo
Allow: /folder
Allow: /start
Allow: /spreadsheet
Allow: /forms
Allow: /macros
Allow: /keep
Allow: /static
Allow: /drive/
Disallow: /templateabuse
Disallow: /
```

showing a clear intent to allow "/file".

and here's the error I get when I try to save this page: https://drive.google.com/file/d/1SDlPNIl02BH-q-itDAR1nMNJxGOB_iCz/view

![image](https://user-images.githubusercontent.com/233815/32710538-f16c8dde-c806-11e7-9def-6e1d58c27dfa.png)

**Comment by anjackson** [comment]
That's a Internet Archive playback issue rather than anything to do with Heritrix.  I recommend you drop them a line via https://archive.org/about/contact.php

**Comment by nlevitt** [comment]
Doesn't seem to be an issue anymore, was able to save the url just now.
https://web.archive.org/web/20190314182509/https://drive.google.com/file/d/1SDlPNIl02BH-q-itDAR1nMNJxGOB_iCz/view
Sorry for not responding sooner :)

**Comment by nightpool** [comment]
thanks for the reply!
