### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by tpegues2** [internetarchive/heritrix3#236]
Hello,

I'm running the latest release of Heritrix version: 3.4.0-20190207 and get the following errors or warnings in my log.  I unable to connect with a browser as a results.  Currently running it on RH7 with java 8. I applied the same fix from an earlier release 3.2 to make it work with java 8 on RH7. Is there something I need to different with this release in order for it to work with java8?

Here are my logs:

Verify in browser before accepting exception.
2019-02-15 16:39:28.122 WARNING thread-1 org.archive.crawler.framework.Engine.findJobConfigs() invalid job directory: ./jobs/._.gitignore where job expected from: ./jobs/._.gitignore
2019-02-15 16:39:28.145 WARNING thread-1 org.archive.crawler.framework.Engine.findJobConfigs() invalid job directory: ./jobs/.gitignore where job expected from: ./jobs/.gitignore
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#
StaticLoggerBinder for further details.
engine listening at port 8443

**Comment by nlevitt** [comment]
Hi @tpegues2, I think the SLF4J messages might be a red herring. What happens when you try to connect with your browser? You might also try `curl -k https://localhost:8443/` which may or many give a clearer indication of the issue.

**Comment by anjackson** [comment]
Thanks @nlevitt. We should probably ship with a SLF4J implementation (at UKWA we build on `heritrix-contrib` which pulls in `slf4j-log4j` so I hadn't noticed the gap), but this only silences logging on dependencies that use `slf4j-api` so is unlikely to be causing the problem.

**Comment by tpegues2** [comment]
Thanks guys!!!  You helped me look at the issue differently and understand that my access was being blocked to the port and my connection was simply being rejected.  All is well !!
