### ISSUE TITLE
Failed DNS requests remain enqueued

### ISSUE THREAD

**Issue by hannakoppelaar** [internetarchive/heritrix3#252]
It seems that failed DNS requests remain enqueued. This can keep a crawl job in the RUNNING state, long (i.e. hours) after it has fetched all its fetchable URIs.

This behaviour can be reproduced by creating a job with just one seed, containing a hostname that does not exist. Heritrix will put this job in the RUNNING state, while effectively doing nothing for (IIRC) about 7 hours.

This is somewhat of a pain for the Web Curator Tool, because we use the number of currently running Heritrix jobs to determine whether enough resources are available to start a new crawl job. 

Is this easy to fix? Or is there perhaps an easy way to mitigate this issue, e.g. via the scripting API?

This issue seems to be related to #234 and #198.

**Comment by nlevitt** [comment]
This is the usual slow retry cycle. Quoting https://github.com/internetarchive/heritrix3/wiki/unexpectedly-slow-crawling-on-idle-crawler

> If the sites still in rotation are spending many minutes between retries, then they are in the 'slow retry' cycle which is triggered by a failure to get any response at all from the target server. By default, such retries are spaced at 900 seconds (15 minutes), and the total number of such retries is 30. (See retryDelay and maxRetries.) Thus, it will take 30x15m == over 7 hours to definitively give up on a URI, logging it as a failure, and moving on to the next URI on the same host.

I confirmed this by running a crawl with these settings on the frontier:
```
  <property name="retryDelaySeconds" value="3" />
  <property name="maxRetries" value="10" />
```
As expected, the crawl finished in about 30 seconds and crawl.log looked like this (note `10t` means 10 tries):
```
2019-04-12T18:30:23.722Z    -1          - dns:example.example P http://example.example/example text/dns #002 20190412183023720+0 - - 10t
2019-04-12T18:30:26.746Z    -6          - http://example.example/example - - unknown #002 - - - 2t
```

**Comment by nlevitt** [comment]
I'm gonna close this issue for now.
