### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [internetarchive/heritrix3#261]
Hi
The following lines have cryptographic API misuses. <br> File name => modules/src/main/java/org/archive/modules/writer/Kw3WriterProcessor.java: Line number => 369: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => modules/src/main/java/org/archive/modules/writer/Kw3WriterProcessor.java: Line number => 371: API name => MessageDigest:<BR> File name => modules/src/main/java/org/archive/modules/extractor/HTTPContentDigest.java: Line number => 137: API name => MessageDigest:First parameter (with value "SHA1") should be any of {SHA-256, SHA-384, SHA-512}<BR>

**Comment by ato** [comment]
Unhelpful bot
