### ISSUE TITLE
Do not treat all URLs from link/@href tags as embeds.

### ISSUE THREAD

**Issue by kris-sigur** [internetarchive/heritrix3#263]
Currently all URLs extracted from `href` attributes on `link` tags are treated as embeds (hop type E).

This makes perfect sense for when the link is to a stylesheet (`ref='stylesheet`), but is just wrong in many other scenarios.

The ExtractorHTML should be modified to take the `rel` attribute into account in determining the type of link, E or L.

**Comment by ato** [comment]
MDN has a table here listing the rel values and whether they should be considered links or resources:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel

Definitely should still be treated as embed:
* icon
* stylesheet

There's a bunch of preload ones which I'm a little uncertain what to do with. It probably makes sense to treat them as embed but potentially they could point at documents too:
* modulepreload
* pingback
* prefetch
* preload
* prerender

I think we should completely ignore these two as they are just supposed to make the browser prefetch DNS or pre-open a connection and don't necessarily indicate the URL of a valid resource:
* dns-prefetch
* preconnect
