### ISSUE TITLE
Integrate "smart" URI queue

### ISSUE THREAD

**Issue by lpla** [internetarchive/heritrix3#284]
Hello `heritrix` devs. I am trying to design and code a queue/cost function for `heritrix` that can be used for parallel language data crawling in [`bitextor`](https://github.com/bitextor/bitextor/) project.

The idea is that we could train a system, or create enough rules, that could give crawling priority to URIs that are more likely to contain translated documents, given that we have limited crawling time and we cannot afford to completely download most of websites.

I am reading [`javadoc`](https://www.javadoc.io/doc/org.archive.heritrix/heritrix-engine/3.4.0-20190418) and part of the [Frontier code](https://github.com/internetarchive/heritrix3/blob/aa705bef2eb8fbbb9aeb56995e713a7b6ba0ed00/engine/src/main/java/org/archive/crawler/prefetch/FrontierPreparer.java), so I would like to know if I am well focused.

To achieve what I described I guess that I would need to create a class that `extends CostAssignmentPolicy` and [costOf](https://github.com/internetarchive/heritrix3/blob/aa705bef2eb8fbbb9aeb56995e713a7b6ba0ed00/engine/src/main/java/org/archive/crawler/frontier/UnitCostAssignmentPolicy.java#L34) will return the "smart" values instead of 1. I guess that the default queue should work for me.

To get this integrated so it can be selected with `prefetch/FrontierPreparer.java` when reading the beans config file `costAssignmentPolicy` property I guess that I would need to compile `heritrix` with my class in it.

Am I too lost? Is there another (better or canonical) way to do what I am proposing?

**Comment by anjackson** [comment]
I think you want the [`UriPrecedencePolicy`](https://github.com/internetarchive/heritrix3/blob/05811705ed996122bea1f4e034c1ed5f7a07240f/engine/src/main/java/org/archive/crawler/frontier/precedence/UriPrecedencePolicy.java) hook. 

It looks like this can be set to [CostUriPrecedencePolicy](https://github.com/internetarchive/heritrix3/blob/05811705ed996122bea1f4e034c1ed5f7a07240f/engine/src/main/java/org/archive/crawler/frontier/precedence/CostUriPrecedencePolicy.java). This means the Cost would have the affect you want, but the default behaviour is that the cost is used to enforce queue rotation when you have more queues (usually this means more hosts) than you have ToeThreads.

**Comment by ato** [comment]
@anjackson, looks to me like CostUriPrecedencePolicy is the default, but I might be missing something that overrides this:

https://github.com/internetarchive/heritrix3/blob/aa705bef2eb8fbbb9aeb56995e713a7b6ba0ed00/engine/src/main/java/org/archive/crawler/prefetch/FrontierPreparer.java#L116-L119

@lpa, your proposed approach sounds reasonable to me but I haven't tried it before myself.

> I guess that I would need to compile heritrix with my class in it.

That's indeed probably the easiest way to get started. Heritrix's unit tests take a while so you might find `mvn package -DskipTests` useful to skip them.

What some people do is create new Maven project that pulls in Heritrix as a dependency and add in whatever extra classes and dependencies they need. That's probably the approach I'd take myself in the long term.

e.g. the UKWA's extra bits: https://github.com/ukwa/ukwa-heritrix/blob/master/pom.xml
