### ISSUE TITLE
Java interface text editor error when saving crawler-beans.cxml

### ISSUE THREAD

**Issue by ArthHoff** [internetarchive/heritrix3#293]
Hi,
Since the August 2019 releases I am unable to save the crawler-beans.cxml from the editor. The last version of Heritrix that works for me is: 3.4.0-SNAPSHOT-2019-08-05T04:18:15Z.
I've tried on different machines and the behaviour is the same.
When I click save I get the following message:
An error occurred
You may be able to recover and try something else by going back. 

![image](https://user-images.githubusercontent.com/24282952/72411469-7384a280-37b2-11ea-8c72-2759f8e3402d.png)
![image](https://user-images.githubusercontent.com/24282952/72411491-8008fb00-37b2-11ea-9f5b-d3ad6319ac50.png)
Thanks

**Comment by ato** [comment]
I can reproduce. It's returning `405 Method Not Allowed`. This was likely introduced by #283, but I could have sworn I tested this.

Thanks for reporting, I'll try to have a fix soon.

**Comment by ArthHoff** [comment]
Thank you so much for the quick fix.
