### ISSUE TITLE
ObjectIdentityBdbManualCacheTest is slow

### ISSUE THREAD

**Issue by hennekey** [internetarchive/heritrix3#297]
>[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 221.574 s - in org.archive.util.ObjectIdentityBdbManualCacheTest

This makes development slow as it takes too long to realistically run the unit tests as often as I would like.

**Comment by ato** [comment]
I agree, I've been regularly disabling this and also BloomFilterTest in my local dev environment. I think unless they can be sped up, slow tests like these should be disabled by default and only opt-in if you're actually working on the relevant code.

**Comment by hennekey** [comment]
It looks like there's a lot of time spent in Kryo methods for this particular test.

**Comment by hennekey** [comment]
By [adding the default constructor to `IdentityCacheableWrapper`](https://github.com/internetarchive/heritrix3/commit/9008d222d5171e919e17b5942437f14625e08892) I was able to speed the test up a bunch:
>[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 111.517 s - in org.archive.util.ObjectIdentityBdbManualCacheTest

**Comment by hennekey** [comment]
@ato Maybe I can address BloomFilter64bitTest  too https://github.com/internetarchive/heritrix3/issues/299

**Comment by hennekey** [comment]
Fixed in #298
