### ISSUE TITLE
Usable variables, e.g. for warcWriter template

### ISSUE THREAD

**Issue by Querela** [internetarchive/heritrix3#363]
The WarcWriter template allows usage of various variables:
`${prefix}-${timestamp17}-${serialno}-${heritrix.pid}~${heritrix.hostname}~${heritrix.port}" `

But I have not found any documentation of all available variables, e. g. is there a variable about the current jobname if I want to include the jobname into the warc filename?
Even looking through the source did not give me any complete list of variables. So, can anyone point me somewhere to look at?

And I'm not sure where I can even test them? (ScriptingConsole but how?, Browse Beans seems not to work...)

**Comment by ato** [comment]
Local properties ([source](https://github.com/iipc/webarchive-commons/blob/63824fc81c155facd4f4f5dfb0529a7f388d90a8/src/main/java/org/archive/io/WriterPoolMember.java#L270-L285)):
* prefix
* serialno
* timestamp17
* timestamp14

Heritrix system properties: ([source](https://github.com/internetarchive/heritrix3/blob/adac067ea74b5a89f631ef771e2f598819bac6c4/engine/src/main/java/org/archive/crawler/Heritrix.java#L393-L418))
* heritrix.port
* heritrix.hostname
* heritrix.runtimeName (usually PID@HOSTNAME)
* heritrix.pid

General Java system properties. You can get a list with `java -XshowSettings:properties --version`

> is there a variable about the current jobname if I want to include the jobname into the warc filename?

Unless it can be done at the Spring xml level somehow I don't think this is possible with the current code.

> And I'm not sure where I can even test them?

The code doesn't seem to be structured to make separately testing the template expansion feasible.

**Comment by Querela** [comment]
Many thanks. That helps a lot.
I stumbled over the writer properties when tracing dependencies, but the others were not so easy to find.

Ok. About the tests, I almost thought so.
