### ISSUE TITLE
Add WARC-IP-Address header to WARCWriterChainProcessor

### ISSUE THREAD

**Issue by anjackson** [internetarchive/heritrix3#396]
The original `WARCWriterProcessor` added a `WARC-IP-Address` header if the IP of the host is known:

https://github.com/internetarchive/heritrix3/blob/37ce8d694590b0cf8cbe0a38a58c5f8ee719c4f0/modules/src/main/java/org/archive/modules/writer/WARCWriterProcessor.java#L278

The newer `WARCWriterChainProcessor` uses a builder for HTTP responses, but this does not include the IP address:

https://github.com/internetarchive/heritrix3/blob/37ce8d694590b0cf8cbe0a38a58c5f8ee719c4f0/modules/src/main/java/org/archive/modules/warc/HttpResponseRecordBuilder.java#L35

Other builders do, like this:

https://github.com/internetarchive/heritrix3/blob/37ce8d694590b0cf8cbe0a38a58c5f8ee719c4f0/modules/src/main/java/org/archive/modules/warc/DnsResponseRecordBuilder.java#L42-L45

It's not clear the original complexity is needed:

https://github.com/internetarchive/heritrix3/blob/37ce8d694590b0cf8cbe0a38a58c5f8ee719c4f0/modules/src/main/java/org/archive/modules/writer/WriterPoolProcessor.java#L378-L401

But if the IP is handy, it should be included in the HTTP response.

**Comment by ato** [comment]
I don't think the IP is handy - A_DNS_SERVER_IP_LABEL is only populated for DNS requests. This explains why the original code looks up the address in the cache.

We could probably do what that TODO:FIXME comment suggests though and have RecordingHttpClientConnection stash the exact ip in the HttpRecorder since it has access to the underlying Socket object when it wraps the input and output streams for recording.

**Comment by ato** [comment]
Oh except Recorder is webarchive-commons. Gah.

**Comment by ato** [comment]
Looks like DNS records are also being written with ip/port label like `/127.0.0.53:53` rather than just the IP address:

```
WARC/1.0
WARC-Type: response
WARC-Target-URI: dns:localhost
WARC-Date: 2021-06-25T04:04:35Z
WARC-IP-Address: /127.0.0.53:53
WARC-Record-ID: <urn:uuid:38d9d425-3a4f-4158-86bf-8a5862ecdd0b>
Content-Type: text/dns
Content-Length: 44
``

**Comment by ato** [comment]
It also turns out `BaseWARCRecordBuilder.getHostAddress(curi)` helper is completely broken with the default config since the RecordBuilders are instantiated by Java code rather than Spring XML so the ServerCache is never autowired into them.
