### ISSUE TITLE
Jobs can get stuck STOPPING with "Interrupt leaving unfinished CrawlURI"

### ISSUE THREAD

**Issue by ato** [internetarchive/heritrix3#420]
We encountered a Heritrix job today that logged this:

> 2021-07-20T13:34:21.083Z INFO STOPPING 20210720013405
> 2021-07-20T13:34:21.580Z SEVERE Interrupt leaving unfinished CrawlURI ToeThread #5: [url] - job may hang (in thread 'ToeThread #5: [url])

The "job may hang" in the log message was accurate, the job became stuck in the STOPPING state and issuing a teardown command through the UI had no effect.

It appears the problem is that when a ToeThread is interrupted it will exit without informing the Frontier that the currently processing CrawlURI is finished. Control flow will jump directly from one of the continueChecks():

https://github.com/internetarchive/heritrix3/blob/846f2bc2cc916cfda6a5cc4cb544459b5c514b04/engine/src/main/java/org/archive/crawler/framework/ToeThread.java#L184

to the InterruptedException catch block:

https://github.com/internetarchive/heritrix3/blob/846f2bc2cc916cfda6a5cc4cb544459b5c514b04/engine/src/main/java/org/archive/crawler/framework/ToeThread.java#L199-L204

without calling frontier.finished(currentCuri):

https://github.com/internetarchive/heritrix3/blob/846f2bc2cc916cfda6a5cc4cb544459b5c514b04/engine/src/main/java/org/archive/crawler/framework/ToeThread.java#L187-L189

this means the queue is never released from the frontier's inProcessQueues set and the frontier managment thread loops forever waiting for it:

https://github.com/internetarchive/heritrix3/blob/846f2bc2cc916cfda6a5cc4cb544459b5c514b04/engine/src/main/java/org/archive/crawler/frontier/AbstractFrontier.java#L390-L397

Intervening by clearing the frontier's inProcessQueues set via the scripting console got it unstuck:

```groovy   
// groovy
appCtx.getBean("frontier").inProcessQueues.clear();
```

**Comment by kris-sigur** [comment]
Your changes seem reasonable.
