### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [internetarchive/heritrix3#429]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by ato** [comment]
As nobody else has replied, I've added a basic SECURITY.md and volunteered the web archiving teams of the National Library of Australia and UK Web Archive as contacts for now in case someone wants to report a Heritrix vulnerability without disclosing it publicly. Other Heritrix maintainers, you're of course more than welcome to edit it and add yourself or your team to the list of contacts.

**Comment by ato** [comment]
In case anyone was curious about what this was about:

https://huntr.dev/bounties/4721488b-6549-4503-9d07-42d0e0155a61/
https://huntr.dev/bounties/c8d52f40-6851-4c23-af27-028fd317de6a/

Unfortunately (or fortunately?) both reports seem to be generic security scanner false positives.
