### ISSUE TITLE
cannot resolve these dependencies

### ISSUE THREAD

**Issue by oldRabbitForz** [internetarchive/heritrix3#443]
![image](https://user-images.githubusercontent.com/38576501/138016636-6e12d82e-2b8c-46df-910a-cd3c5a3b96c8.png)

**Comment by oldRabbitForz** [comment]
<dependency>
            <groupId>org.archive.heritrix</groupId>
            <artifactId>heritrix-commons</artifactId>
            <version>3.4.0-20210923</version>
        </dependency>
        <dependency>
            <groupId>org.archive.heritrix</groupId>
            <artifactId>heritrix-modules</artifactId>
            <version>3.4.0-20210923</version>
        </dependency>
        <dependency>
            <groupId>org.archive.heritrix</groupId>
            <artifactId>heritrix-engine</artifactId>
            <version>3.4.0-20210923</version>
        </dependency>

**Comment by oldRabbitForz** [comment]
@ato

**Comment by oldRabbitForz** [comment]
i'm using idea ide.  a program with Heritrix3 based on springboot.

**Comment by oldRabbitForz** [comment]
when i download these dependencies, the mistakes occured.so how  can i resolve these problems.thanks!

**Comment by oldRabbitForz** [comment]
@ato

**Comment by ato** [comment]
If you're including it as a dependency in Maven project maybe try adding these repositories to your pom.xml file, although I would normally expect them to be included automatically. You may also need [Andy's workaround](https://github.com/internetarchive/heritrix3/pull/310#issuecomment-857543812).

```xml
    <repositories>
        <repository>
            <id>builds.archive.org,maven2</id>
            <url>http://builds.archive.org/maven2</url>
        </repository>
        <repository>
            <id>oracleReleases</id>
            <name>Oracle Released Java Packages</name>
            <url>https://download.oracle.com/maven</url>
        </repository>
    </repositories>
```

If you're using Gradle, I can't help as I've never used it.

However personally I don't recommend embedding Heritrix inside another Java application as it has a lot of dependencies that may cause conflicts and it also does some surprising things like globally seting the JVM's timezone to UTC. I recommend controlling it via the [REST API](https://heritrix.readthedocs.io/en/latest/api.html) if possible.
