### ISSUE TITLE
"java.lang.NoClassDefFoundError: Could not initialize class org.archive.util.CLibrary" on Apple Silicon

### ISSUE THREAD

**Issue by ziodave** [internetarchive/heritrix3#467]
`mvn install` fails with `"java.lang.NoClassDefFoundError: Could not initialize class org.archive.util.CLibrary" on Apple Silicon`.

To fix I upgraded the dependency in commons/pom.xml from:

```
		<dependency>
			<groupId>net.java.dev.jna</groupId>
			<artifactId>jna</artifactId>
			<version>3.2.3</version>
		</dependency>
```

to

```
		<dependency>
			<groupId>net.java.dev.jna</groupId>
			<artifactId>jna</artifactId>
			<version>5.10.0</version>
		</dependency>
```

**Comment by ato** [comment]
It seems the only reason Heritrix depends on jna is for creating hard-links and symbolic-links. As of Java 7 are now proper java APIs for these (Files.createLink() and Files.createSymbolicLink()) so I think we could remove the code that uses jna entirely.
