### ISSUE TITLE
Job build fails with NoClassDefFoundError: org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by zhaobm** [internetarchive/heritrix3#482]
严重: Can't create bean 'fetchDns'; Can't create bean 'fetchProcessors'; Can't create bean 'crawlController'; Can't create bean 'frontier'; Can't create bean 'seeds'
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'seeds': Unsatisfied dependency expressed through method 'setSeedListeners' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'frontier': Unsatisfied dependency expressed through method 'setCrawlController' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'crawlController': Unsatisfied dependency expressed through method 'setFetchChain' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fetchProcessors' defined in URL [file:/D:/MyProduct/heritrix3/./jobs/spider2/crawler-beans.cxml]: Cannot resolve reference to bean 'fetchDns' while setting bean property 'processors' with key [2]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fetchDns' defined in URL [file:/D:/MyProduct/heritrix3/./jobs/spider2/crawler-beans.cxml]: Instantiation of bean failed; nested exception is java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

**Comment by ato** [comment]
I have seen this error before when running Heritrix under an IDE with the wrong classpath. For example running it with only the 'heritrix-engine' module on the classpath. If you are running from IDE make sure you run Heritrix from the 'heritrix (1) org.archive.heritrix' [dist] or 'heritrix-contrib' modules.

![image](https://user-images.githubusercontent.com/10588/167970474-d0fd2215-b567-45d3-8a30-18d69f1e88de.png)

**Comment by zhaobm** [comment]
The problem has already been solved.thank you so much
