### ISSUE TITLE
archive web crawler - crawl speed

### ISSUE THREAD

**Issue by solaceten** [internetarchive/heritrix3#562]
Hi there

I am a server administrator.  I have been finding that the web crawler for [archive.org](http://archive.org/) has been crawling websites on our servers at a very overwhelming rate  - causing servers to become unstable and have very high server load.

I am wondering if your crawler has a robots.txt or equivalent code that will allow us to slow down your crawler speed or crawl rate (similar to the google search engine [speed control mentioned here ](https://support.google.com/webmasters/answer/48620))

Thank you for your assistance.

**Comment by anjackson** [comment]
Please contact the Internet Archive directly, as this site is used for collaborative development, and they may miss complaints raised here.

See https://archive.org/about/contact.php or contact info@archive.org
